{
  "swagger": "2.0",
  "schemes": [
    "https"
  ],
  "info": {
    "version": "1.0.0",
    "description": "SMRT Bundle Upgrade Server Swagger 2.0 specification",
    "title": "SMRT Bundle Upgrade Server"
  },
  "host": "localhost:8081",
  "x-wso2-security": {
    "apim": {
      "x-wso2-scopes": [
        {
          "roles": "Internal/PbAdmin,Internal/PbLabTech",
          "name": "run-design",
          "key": "run-design",
          "description": "Run Design Authorization"
        },
        {
          "roles": "Internal/PbAdmin,Internal/PbLabTech,Internal/PbBioinformatician",
          "name": "run-qc",
          "key": "run-qc",
          "description": "Run QC Authorization"
        },
        {
          "roles": "Internal/PbAdmin,Internal/PbLabTech",
          "name": "sample-setup",
          "key": "sample-setup",
          "description": "Sample Setup Authorization"
        },
        {
          "roles": "Internal/PbAdmin,Internal/PbLabTech,Internal/PbBioinformatician",
          "name": "data-management",
          "key": "data-management",
          "description": "Data Management Authorization"
        },
        {
          "roles": "Internal/PbAdmin,Internal/PbLabTech,Internal/PbBioinformatician",
          "name": "analysis",
          "key": "analysis",
          "description": "SMRT Analysis Authorization"
        }
      ]
    }
  },
  "paths": {
    "/status": {
      "get": {
        "description": "Get the SMRT Link System Status containing system metadata, such as SL System Id, uptime and status message.",
        "produces": [
          "application/json"
        ],
        "x-throttling-tier": "Unlimited",
        "responses": {
          "default": {
            "description": "Failed to get Server status likely means the server is down"
          },
          "200": {
            "description": "SMRT Link Analysis Server Status",
            "schema": {
              "$ref": "#/definitions/SmrtServerStatus"
            }
          }
        },
        "x-auth-type": "Application & Application User"
      }
    },
    "/smrt-link/bundles": {
      "get": {
        "deprecated": true,
        "description": "Get a list of all registered bundles (active or inactive) in the system. This should ONLY be used for 5.0.0",
        "x-scope": "data-management",
        "produces": [
          "application/json"
        ],
        "x-throttling-tier": "Unlimited",
        "responses": {
          "default": {
            "description": "Unable to get bundle service. Bundle service is down"
          },
          "200": {
            "description": "List of PacBio Data Bundless",
            "schema": {
              "$ref": "#/definitions/PacBioDataBundleList"
            }
          }
        },
        "x-auth-type": "Application & Application User"
      }
    },
    "/smrt-link/bundles/{bundleType}": {
      "get": {
        "deprecated": true,
        "description": "Get a list of all registered bundles by bundle type (active or inactive) in the system. This should ONLY be used for 5.0.0",
        "x-scope": "data-management",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "Bundle type id (e.g., 'chemistry', 'pbtestdata')",
            "required": true,
            "type": "string",
            "name": "bundleType",
            "in": "path"
          }
        ],
        "x-throttling-tier": "Unlimited",
        "responses": {
          "default": {
            "description": "Unable to find any PacBio Data Bundle(s) with provide bundle type"
          },
          "200": {
            "description": "List of PacBio Data Bundles for provide bundle type",
            "schema": {
              "$ref": "#/definitions/PacBioDataBundleList"
            }
          }
        },
        "x-auth-type": "Application & Application User"
      }
    },
    "/smrt-link/bundles/{bundleType}/{bundleVersion}": {
      "get": {
        "deprecated": true,
        "description": "Get a PacBio Data Bundle by Id (bundleType, bundleVersion). This should ONLY be used for 5.0.0",
        "x-scope": "data-management",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "Bundle type id (e.g., 'chemistry', 'pbtestdata')",
            "required": true,
            "type": "string",
            "name": "bundleType",
            "in": "path"
          },
          {
            "description": "Bundle version (e.g., 1.2.3) This should adhere to the Semantic Version scheme",
            "required": true,
            "type": "string",
            "name": "bundleVersion",
            "in": "path"
          }
        ],
        "x-throttling-tier": "Unlimited",
        "responses": {
          "default": {
            "description": "Unable to find PacBio Data Bundle for bundle type and bundle version provided"
          },
          "200": {
            "description": "PacBio Data Bundle",
            "schema": {
              "$ref": "#/definitions/PacBioDataBundle"
            }
          }
        },
        "x-auth-type": "Application & Application User"
      }
    },
    "/smrt-link/bundles/{bundleType}/{bundleVersion}/download": {
      "get": {
        "deprecated": true,
        "description": "Download a PacBio Data Bundle TGZ by Id (bundleType, bundleVersion)",
        "x-scope": "data-management",
        "produces": [
          "text/plain; charset=UTF-8"
        ],
        "parameters": [
          {
            "description": "Bundle type id (e.g., 'chemistry', 'pbtestdata')",
            "required": true,
            "type": "string",
            "name": "bundleType",
            "in": "path"
          },
          {
            "description": "Bundle version (e.g., 1.2.3) This should adhere to the Semantic Version scheme",
            "required": true,
            "type": "string",
            "name": "bundleVersion",
            "in": "path"
          }
        ],
        "x-throttling-tier": "Unlimited",
        "responses": {
          "default": {
            "description": "Unable to find PacBio Data Bundle for bundle type and bundle version provided"
          },
          "200": {
            "description": "PacBio Data TGZ Bundle"
          }
        },
        "x-auth-type": "Application & Application User"
      }
    },
    "/api/v2/bundles/{pacbioSystemVersion}/bundles": {
      "get": {
        "description": "Get a list of all registered bundles (active or inactive) in the system",
        "x-scope": "data-management",
        "produces": [
          "application/json"
        ],
        "x-throttling-tier": "Unlimited",
        "parameters": [
          {
            "description": "PacBio System Release version (e.g., 5.0.0)",
            "required": true,
            "type": "string",
            "name": "pacbioSystemVersion",
            "in": "path"
          }
        ],
        "responses": {
          "default": {
            "description": "Unable to get bundle service. Bundle service is down"
          },
          "200": {
            "description": "List of PacBio Data Bundless",
            "schema": {
              "$ref": "#/definitions/PacBioDataBundleList"
            }
          }
        },
        "x-auth-type": "Application & Application User"
      }
    },
    "/api/v2/bundles/{pacbioSystemVersion}/bundles/{bundleType}": {
      "get": {
        "description": "Get a list of all registered bundles by bundle type (active or inactive) in the system",
        "x-scope": "data-management",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "PacBio System Release version (e.g., 5.0.0)",
            "required": true,
            "type": "string",
            "name": "pacbioSystemVersion",
            "in": "path"
          },
          {
            "description": "Bundle type id (e.g., 'chemistry', 'pbtestdata')",
            "required": true,
            "type": "string",
            "name": "bundleType",
            "in": "path"
          }
        ],
        "x-throttling-tier": "Unlimited",
        "responses": {
          "default": {
            "description": "Unable to find any PacBio Data Bundle(s) with provide bundle type"
          },
          "200": {
            "description": "List of PacBio Data Bundles for provide bundle type",
            "schema": {
              "$ref": "#/definitions/PacBioDataBundleList"
            }
          }
        },
        "x-auth-type": "Application & Application User"
      }
    },
    "/api/v2/bundles/{pacbioSystemVersion}/bundles/{bundleType}/{bundleVersion}": {
      "get": {
        "description": "Get a PacBio Data Bundle by Id (bundleType, bundleVersion)",
        "x-scope": "data-management",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "PacBio System Release version (e.g., 5.0.0)",
            "required": true,
            "type": "string",
            "name": "pacbioSystemVersion",
            "in": "path"
          },
          {
            "description": "Bundle type id (e.g., 'chemistry', 'pbtestdata')",
            "required": true,
            "type": "string",
            "name": "bundleType",
            "in": "path"
          },
          {
            "description": "Bundle version (e.g., 1.2.3) This should adhere to the Semantic Version scheme",
            "required": true,
            "type": "string",
            "name": "bundleVersion",
            "in": "path"
          }
        ],
        "x-throttling-tier": "Unlimited",
        "responses": {
          "default": {
            "description": "Unable to find PacBio Data Bundle for bundle type and bundle version provided"
          },
          "200": {
            "description": "PacBio Data Bundle",
            "schema": {
              "$ref": "#/definitions/PacBioDataBundle"
            }
          }
        },
        "x-auth-type": "Application & Application User"
      }
    },
    "/api/v2/bundles/{pacbioSystemVersion}/{bundleType}/{bundleVersion}/download": {
      "get": {
        "description": "Download a PacBio Data Bundle TGZ by Id (bundleType, bundleVersion)",
        "x-scope": "data-management",
        "produces": [
          "text/plain; charset=UTF-8"
        ],
        "parameters": [
          {
            "description": "PacBio System Release version (e.g., 5.0.0)",
            "required": true,
            "type": "string",
            "name": "pacbioSystemVersion",
            "in": "path"
          },
          {
            "description": "Bundle type id (e.g., 'chemistry', 'pbtestdata')",
            "required": true,
            "type": "string",
            "name": "bundleType",
            "in": "path"
          },
          {
            "description": "Bundle version (e.g., 1.2.3) This should adhere to the Semantic Version scheme",
            "required": true,
            "type": "string",
            "name": "bundleVersion",
            "in": "path"
          }
        ],
        "x-throttling-tier": "Unlimited",
        "responses": {
          "default": {
            "description": "Unable to find PacBio Data Bundle for bundle type and bundle version provided"
          },
          "200": {
            "description": "PacBio Data TGZ Bundle"
          }
        },
        "x-auth-type": "Application & Application User"
      }
    },
    "/api/v2/swagger": {
      "get": {
        "description": "Returns the swagger file as JSON",
        "produces": [
          "application/json"
        ],
        "x-throttling-tier": "Unlimited",
        "responses": {
          "200": {
            "description": "Return swagger file as JSON"
          }
        },
        "x-auth-type": "Application & Application User"
      }
    }
  },
  "definitions": {
    "SmrtServerStatus": {
      "type": "object",
      "title": "SMRT Server Status",
      "description": "An summary of the SMRT Server instance, current state and status.",
      "properties": {
        "uuid": {
          "type": "string",
          "title": "Server UUID",
          "description": "UUID of SMRT Server instance"
        },
        "version": {
          "type": "string",
          "title": "SMRT Analysis Services Version",
          "description": "The Version of the SMRT Analysis Services Version. Note, this is not the SMRT Link System version. See services/manifests to see details."
        },
        "id": {
          "type": "string",
          "title": "SMRT Server Type Id",
          "description": "SMRT Server Type Id"
        },
        "uptime": {
          "type": "integer",
          "format": "int64",
          "title": "Uptime",
          "description": "Uptime of the Server (in milliseconds)"
        },
        "message": {
          "type": "string",
          "title": "Status Message",
          "description": "SMRT Analysis Service message status."
        },
        "user": {
          "type": "string",
          "title": "User",
          "description": "User that the SMRT Analysis Services are launched by"
        }
      },
      "required": [
        "uuid",
        "version",
        "id",
        "uptime",
        "message",
        "user"
      ],
      "example": {
        "uuid": "8da44054-4013-420d-b547-d11a892fe7bb",
        "version": "0.3.0-bbcc1b5",
        "id": "smrtlink_analysis",
        "uptime": 210242144,
        "message": "Services have been up for 58 hours, 24 minutes and 2.144 seconds.",
        "user": "tesla"
      }
    },
    "PacBioDataBundle": {
      "properties": {
        "createdBy": {
          "description": "Author of the PacBio Data Bundle",
          "title": "Author",
          "type": "string"
        },
        "importedAt": {
          "description": "When the PacBio Data Bundle was imported at",
          "title": "Imported At",
          "type": "string"
        },
        "isActive": {
          "default": false,
          "description": "Get the activation status of PacBio Data Bundle",
          "title": "Is Active",
          "type": "boolean"
        },
        "typeId": {
          "description": "Bundle Type Id",
          "title": "Bundle Type",
          "type": "string"
        },
        "version": {
          "description": "Bundle Version. This should adhere to the SemVer to ensure consistent sorting of Data Bundles by Version",
          "title": "Version",
          "type": "string"
        }
      },
      "required": [
        "importedAt",
        "version",
        "isActive",
        "createdBy",
        "typeId"
      ],
      "example": {
        "createdBy": "build",
        "importedAt": "2017-03-28T13:16:15.048Z",
        "isActive": true,
        "typeId": "chemistry",
        "version": "4.0.0"
      },
      "type": "object"
    },
    "PacBioDataBundleList": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/PacBioDataBundle"
      },
      "example": [
        {
          "createdBy": "build",
          "importedAt": "2017-03-28T13:16:15.048Z",
          "isActive": true,
          "typeId": "chemistry",
          "version": "4.0.0"
        },
        {
          "createdBy": "mkocher",
          "importedAt": "2017-03-28T13:16:15.062Z",
          "isActive": false,
          "typeId": "chemistry",
          "version": "4.1.0"
        }
      ]
    }
  }
}
